arquivo = open("arquivo_teste.txt", "w")
arquivo.write("Este é meu primeiro arquivo.\n")
arquivo.write("Vou gravar nele um poema:\n")
arquivo.write("Poeminha do Contra – Mario Quintana\n")
arquivo.write("Todos estes que aí estão\n")
arquivo.write("Atravancando o meu caminho,\n")
arquivo.write("Eles passarão.\n")
arquivo.write("Eu passarinho!\n")
arquivo.close()